### ISSUE TITLE
No highlights or linking of spells

### ISSUE THREAD

**Issue by LootFever** [Loadren/spell-inspect-mode#1]
The inspect mode works (even though im kinda sad I can't just set shift as trigger keybind).
But the inspected spell doesn't show any of the links whatsoever. 
Even hovering over a spell that should be marked as a link does nothing.
![image](https://github.com/user-attachments/assets/0463c609-96e6-4a03-b88b-f4cf544684be)

**Comment by Loadren** [comment]
Hey,
Thank you for opening an issue!
On what version of the addon are you?
The current version is this one : 
![image](https://github.com/user-attachments/assets/0c1f8259-a08d-4e14-bb98-a169f18b1f8e)

**Comment by Loadren** [comment]
I figured out the issue. The problem was that I was calling the function to load the Spell & Talent tables before the SpellBook was accessible. This caused the addon to work correctly on a `/reload` but not on a fresh login. To address this, I changed the event handling to trigger on the `SPELLS_CHANGED` event, which specifically fires when the SpellBook is fully loaded and accessible. This ensures that the addon loads the correct spell and talent data consistently on both login and reload.
Update your addon in 10/15 minutes and it should be fixed!
